-- CUSTOMERS
CREATE TABLE "DBS211_232NEE26"."CUSTOMERS" (
	"CUSTOMERNUMBER" NUMBER(*, 0) NOT NULL ENABLE,
	"CUSTOMERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CONTACTLASTNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CONTACTFIRSTNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"PHONE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"ADDRESSLINE1" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"ADDRESSLINE2" VARCHAR2(50 BYTE) DEFAULT NULL,
	"CITY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"STATE" VARCHAR2(50 BYTE) DEFAULT NULL,
	"POSTALCODE" VARCHAR2(15 BYTE) DEFAULT NULL,
	"COUNTRY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"SALESREPEMPLOYEENUMBER" NUMBER(*, 0) DEFAULT NULL,
	"CREDITLIMIT" NUMBER(10, 2) DEFAULT NULL,
	PRIMARY KEY ("CUSTOMERNUMBER") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE,
	CONSTRAINT "CUST_SALESREP_FK" FOREIGN KEY ("SALESREPEMPLOYEENUMBER") REFERENCES "DBS211_232NEE26"."EMPLOYEES" ("EMPLOYEENUMBER") ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";
-- EMPLOYEES
CREATE TABLE "DBS211_232NEE26"."EMPLOYEES" (
	"EMPLOYEENUMBER" NUMBER(*, 0) NOT NULL ENABLE,
	"LASTNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"FIRSTNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"EXTENSION" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"OFFICECODE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"REPORTSTO" NUMBER(*, 0) DEFAULT NULL,
	"JOBTITLE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	PRIMARY KEY ("EMPLOYEENUMBER") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE,
	CONSTRAINT "EMP_RTEMP_FK" FOREIGN KEY ("REPORTSTO") REFERENCES "DBS211_232NEE26"."EMPLOYEES" ("EMPLOYEENUMBER") ENABLE,
	CONSTRAINT "EMP_OFFICE_FK" FOREIGN KEY ("OFFICECODE") REFERENCES "DBS211_232NEE26"."OFFICES" ("OFFICECODE") ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";
-- OFFICES
CREATE TABLE "DBS211_232NEE26"."OFFICES" (
	"OFFICECODE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"CITY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"PHONE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"ADDRESSLINE1" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"ADDRESSLINE2" VARCHAR2(50 BYTE) DEFAULT NULL,
	"STATE" VARCHAR2(50 BYTE) DEFAULT NULL,
	"COUNTRY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"POSTALCODE" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"TERRITORY" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PRIMARY KEY ("OFFICECODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";
-- ORDERDETAILS
CREATE TABLE "DBS211_232NEE26"."ORDERDETAILS" (
	"ORDERNUMBER" NUMBER(*, 0) NOT NULL ENABLE,
	"PRODUCTCODE" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"QUANTITYORDERED" NUMBER(*, 0) NOT NULL ENABLE,
	"PRICEEACH" NUMBER(10, 2) NOT NULL ENABLE,
	"ORDERLINENUMBER" NUMBER(*, 0) NOT NULL ENABLE,
	PRIMARY KEY ("ORDERNUMBER", "PRODUCTCODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE,
	CONSTRAINT "ORDDET_ORDNUM_FK" FOREIGN KEY ("ORDERNUMBER") REFERENCES "DBS211_232NEE26"."ORDERS" ("ORDERNUMBER") ENABLE,
	CONSTRAINT "ORDDET_PRODCODE_FK" FOREIGN KEY ("PRODUCTCODE") REFERENCES "DBS211_232NEE26"."PRODUCTS" ("PRODUCTCODE") ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";
-- ORDERS
CREATE TABLE "DBS211_232NEE26"."ORDERS" (
	"ORDERNUMBER" NUMBER(*, 0) NOT NULL ENABLE,
	"ORDERDATE" DATE NOT NULL ENABLE,
	"REQUIREDDATE" DATE NOT NULL ENABLE,
	"SHIPPEDDATE" DATE DEFAULT NULL,
	"STATUS" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(500 BYTE),
	"CUSTOMERNUMBER" NUMBER(*, 0) NOT NULL ENABLE,
	PRIMARY KEY ("ORDERNUMBER") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE,
	CONSTRAINT "ORDERS_CUST_FK" FOREIGN KEY ("CUSTOMERNUMBER") REFERENCES "DBS211_232NEE26"."CUSTOMERS" ("CUSTOMERNUMBER") ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";
-- PAYMENTS
CREATE TABLE "DBS211_232NEE26"."PAYMENTS" (
	"CUSTOMERNUMBER" NUMBER(*, 0) NOT NULL ENABLE,
	"CHECKNUMBER" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"PAYMENTDATE" DATE NOT NULL ENABLE,
	"AMOUNT" NUMBER(10, 2) NOT NULL ENABLE,
	PRIMARY KEY ("CUSTOMERNUMBER", "CHECKNUMBER") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE,
	CONSTRAINT "PAYMENTS_CUSTNUM_FK" FOREIGN KEY ("CUSTOMERNUMBER") REFERENCES "DBS211_232NEE26"."CUSTOMERS" ("CUSTOMERNUMBER") ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";
-- PRODUCTLINES
CREATE TABLE "DBS211_232NEE26"."PRODUCTLINES" (
	"PRODUCTLINE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"TEXTDESCRIPTION" VARCHAR2(4000 BYTE) DEFAULT NULL,
	"HTMLDESCRIPTION" VARCHAR2(4000 BYTE),
	"IMAGE" VARCHAR2(150 BYTE),
	PRIMARY KEY ("PRODUCTLINE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";
-- PRODUCTS
CREATE TABLE "DBS211_232NEE26"."PRODUCTS" (
	"PRODUCTCODE" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"PRODUCTNAME" VARCHAR2(70 BYTE) NOT NULL ENABLE,
	"PRODUCTLINE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"PRODUCTSCALE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"PRODUCTVENDOR" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"PRODUCTDESCRIPTION" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
	"QUANTITYINSTOCK" NUMBER(*, 0) NOT NULL ENABLE,
	"BUYPRICE" NUMBER(10, 2) NOT NULL ENABLE,
	"MSRP" NUMBER(10, 2) NOT NULL ENABLE,
	PRIMARY KEY ("PRODUCTCODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
		INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
	) TABLESPACE "USER_DATA" ENABLE,
	CONSTRAINT "PROD_LINE_FK" FOREIGN KEY ("PRODUCTLINE") REFERENCES "DBS211_232NEE26"."PRODUCTLINES" ("PRODUCTLINE") ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USER_DATA";