/* **************
 CHI-WEI PERNG
 DBS211 - Week 6
 Midterm
 June 14 2023
 ************** */

CREATE TABLE w6Transaction ( 
    transID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    amount NUMBER(9,2) NOT NULL,
    tDate DATE,
    accountID INT NOT NULL    
);


CREATE TABLE w6Account (
    accountID INT PRIMARY KEY,
    custName varchar(50),
    accountType CHAR(1) CHECK (accountType IN ('S', 'C', 'I')),
    balance number (9,2) DEFAULT (0,0)
);

ALTER TABLE w6Transaction
    ADD CONSTRAINT fk_w6Transaction_w6Account FOREIGN KEY (account_id);
    REFERENCES w6Account(accountID);

INSERT INTO w6Account VALUES(1, 'Clint', 'C', 5566.56);
INSERT INTO w6Account VALUES(2, 'Clint', 'S', 1234.56);

SELECT * FROM w6Account;;

COMMOT;

-- simulate moving money $1000 from s to c
-- withdrawal
INSERT INTO w6Transaction VALUES (NULL, -1000, sysdate, 2);
UPDATE w6Account SET balance = balance - 1000 WHERE accountID = 2;
-- deposit
INSERT INTO w6Transaction VALUES (NULL, 1000, sysdate, 1);
UPDATE w6Account SET balance = balance + 1000 WHERE accountID = 1;

COMMIT;

SELECT * FROM w6Account;
SELECT * FROM w6Transaction;

-- How do we intentionally go back
-- ROLLBACK
INSERT INTO w6Transaction VALUE (NULL, -1000, sysdate, 2);
UPDATE w6Account SET balance = balance - 1000 WHERE accountID = 2;
-- deposit
INSERT INTO w6Transaction VALUES (NULL, 1000, sysdate, 1);
UPDATE w6Account SET balance = balance + 1000 WHERE accountID = 1;

ROLLBACK;
-- goes back to the beginning of the current transaction
CREATE VIEW vwTemp AS;
    SELECT * FROM w6Account;

COMMIT;
-- can we partially rollback?

SAVEPOINT w;
INSERT INTO w6Transactions VALUES (NULL, -1000, sysdate, 2);
UPDATE w6Accounts SET balance = balance - 1000 WHERE accountID = 2;
-- deposit
SAVEPOINT d;
INSERT INTO w6Transactions VALUES (NULL, 1000, sysdate, 1);
UPDATE w6Accounts SET balance = balance + 1000 WHERE accountID = 1;
     
SELECT * FROM w6Accounts;

ROLLBACK TO d;
ROLLBACK;